<?php

namespace Database\Seeders;

use App\Models\Handphone;
use Illuminate\Database\Seeder;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class HandphoneSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $handphones = [
            [
                'name' => 'Samsung Galaxy S23 Ultra',
                'price' => 17999000,
                'camera' => 10,
                'battery' => 9,
                'ram' => 10,
                'prosessor' => 10,
                'design' => 9,
                'storage' => 10,
            ],
            [
                'name' => 'iPhone 15 Pro Max',
                'price' => 19999000,
                'camera' => 9,
                'battery' => 8,
                'ram' => 9,
                'prosessor' => 10,
                'design' => 10,
                'storage' => 9,
            ],
            [
                'name' => 'Google Pixel 7 Pro',
                'price' => 12999000,
                'camera' => 10,
                'battery' => 8,
                'ram' => 8,
                'prosessor' => 9,
                'design' => 8,
                'storage' => 8,
            ],
            [
                'name' => 'Xiaomi 13 Ultra',
                'price' => 14999000,
                'camera' => 10,
                'battery' => 9,
                'ram' => 9,
                'prosessor' => 10,
                'design' => 8,
                'storage' => 9,
            ],
            [
                'name' => 'Samsung Galaxy A54',
                'price' => 5999000,
                'camera' => 8,
                'battery' => 9,
                'ram' => 7,
                'prosessor' => 7,
                'design' => 8,
                'storage' => 7,
            ],
            [
                'name' => 'Xiaomi Redmi Note 12 Pro',
                'price' => 3999000,
                'camera' => 8,
                'battery' => 9,
                'ram' => 7,
                'prosessor' => 7,
                'design' => 7,
                'storage' => 7,
            ],
            [
                'name' => 'OnePlus 11',
                'price' => 9999000,
                'camera' => 9,
                'battery' => 8,
                'ram' => 9,
                'prosessor' => 10,
                'design' => 8,
                'storage' => 9,
            ],
            [
                'name' => 'Nothing Phone 2',
                'price' => 7999000,
                'camera' => 8,
                'battery' => 8,
                'ram' => 8,
                'prosessor' => 8,
                'design' => 10,
                'storage' => 8,
            ],
            [
                'name' => 'iPhone 14',
                'price' => 12999000,
                'camera' => 8,
                'battery' => 7,
                'ram' => 8,
                'prosessor' => 9,
                'design' => 8,
                'storage' => 8,
            ],
            [
                'name' => 'Realme GT 5 Pro',
                'price' => 8999000,
                'camera' => 9,
                'battery' => 9,
                'ram' => 9,
                'prosessor' => 10,
                'design' => 8,
                'storage' => 8,
            ],
            [
                'name' => 'Xiaomi Poco F5',
                'price' => 4999000,
                'camera' => 7,
                'battery' => 9,
                'ram' => 8,
                'prosessor' => 8,
                'design' => 7,
                'storage' => 7,
            ],
            [
                'name' => 'Samsung Galaxy S23 FE',
                'price' => 8999000,
                'camera' => 8,
                'battery' => 8,
                'ram' => 8,
                'prosessor' => 9,
                'design' => 8,
                'storage' => 8,
            ],
            [
                'name' => 'Xiaomi Redmi Note 12',
                'price' => 2499000,
                'camera' => 7,
                'battery' => 9,
                'ram' => 6,
                'prosessor' => 6,
                'design' => 7,
                'storage' => 6,
            ],
            [
                'name' => 'Samsung Galaxy A34',
                'price' => 4299000,
                'camera' => 7,
                'battery' => 9,
                'ram' => 7,
                'prosessor' => 7,
                'design' => 7,
                'storage' => 7,
            ],
            [
                'name' => 'Motorola Edge 40',
                'price' => 4999000,
                'camera' => 8,
                'battery' => 8,
                'ram' => 8,
                'prosessor' => 7,
                'design' => 8,
                'storage' => 8,
            ],
            [
                'name' => 'Oppo Reno 10',
                'price' => 5699000,
                'camera' => 8,
                'battery' => 8,
                'ram' => 8,
                'prosessor' => 7,
                'design' => 9,
                'storage' => 7,
            ],
            [
                'name' => 'Vivo V27',
                'price' => 5499000,
                'camera' => 9,
                'battery' => 8,
                'ram' => 8,
                'prosessor' => 8,
                'design' => 8,
                'storage' => 8,
            ],
            [
                'name' => 'Nokia G42',
                'price' => 2999000,
                'camera' => 6,
                'battery' => 9,
                'ram' => 6,
                'prosessor' => 6,
                'design' => 7,
                'storage' => 6,
            ],
            [
                'name' => 'Samsung Galaxy A14',
                'price' => 1999000,
                'camera' => 6,
                'battery' => 8,
                'ram' => 5,
                'prosessor' => 5,
                'design' => 6,
                'storage' => 5,
            ],
            [
                'name' => 'Realme C55',
                'price' => 2499000,
                'camera' => 7,
                'battery' => 8,
                'ram' => 6,
                'prosessor' => 6,
                'design' => 7,
                'storage' => 6,
            ],
            [
                'name' => 'Infinix Note 30',
                'price' => 2299000,
                'camera' => 6,
                'battery' => 9,
                'ram' => 6,
                'prosessor' => 6,
                'design' => 6,
                'storage' => 6,
            ],
            [
                'name' => 'Xiaomi Redmi 12',
                'price' => 1899000,
                'camera' => 6,
                'battery' => 8,
                'ram' => 5,
                'prosessor' => 5,
                'design' => 7,
                'storage' => 5,
            ],
            [
                'name' => 'Vivo Y27',
                'price' => 1999000,
                'camera' => 6,
                'battery' => 9,
                'ram' => 5,
                'prosessor' => 5,
                'design' => 7,
                'storage' => 5,
            ],
            [
                'name' => 'OPPO A78',
                'price' => 2999000,
                'camera' => 7,
                'battery' => 8,
                'ram' => 6,
                'prosessor' => 6,
                'design' => 7,
                'storage' => 6,
            ],
        ];

        foreach ($handphones as $hp) {
            Handphone::create($hp);
        }
    }
}
