name: Ping Supabase to Prevent Pausing

on:
  schedule:
    - cron: "0 */12 * * *" # Runs every 12 hours
  workflow_dispatch: # Allows manual triggering through GitHub UI

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm install @supabase/supabase-js

      - name: Debug environment variables
        run: |
          echo "SUPABASE_URL is set: ${{ secrets.SUPABASE_URL != '' }}"
          echo "SUPABASE_KEY is set: ${{ secrets.SUPABASE_KEY != '' }}"

      - name: Ping Supabase
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: |
          echo "Starting Supabase ping..."
          node -e "
          const { createClient } = require('@supabase/supabase-js');

          // Debug environment variables
          console.log('SUPABASE_URL exists:', !!process.env.SUPABASE_URL);
          console.log('SUPABASE_KEY exists:', !!process.env.SUPABASE_KEY);

          // Hardcoded fallback for testing (remove in production)
          const supabaseUrl = process.env.SUPABASE_URL || 'https://your-project-id.supabase.co';
          const supabaseKey = process.env.SUPABASE_KEY || 'your-anon-key';

          const supabase = createClient(supabaseUrl, supabaseKey);

          async function pingSupabase() {
            try {
              const { data, error } = await supabase.from('handphones').select('id').limit(1);

              if (error) {
                console.error('Error pinging Supabase:', error);
                process.exit(1);
              } else {
                console.log('Successfully pinged Supabase at', new Date().toISOString());
                console.log('Response:', data);
              }
            } catch (err) {
              console.error('Unexpected error:', err);
              process.exit(1);
            }
          }

          pingSupabase();
          "
